name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip wheel
        pip install -rrequirements.txt -rtest_requirements.txt flake8
    - name: Install dependencies for python 3
      if: ${{ matrix.python-version != '2.7' }}
      run: |
        pip install pytest-pythonpath pytest-django
    - name: Test
      run: |
        python setup.py install
        py.test -v tests
    - name: Flake8
      run: |
        flake8 --ignore=E402 .
    - name: Upload coverage.xml to codecov
      if: ${{ matrix.python-version == '3.9' }}
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
